export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className=" flex flex-1 items-center justify-center w-full h-screen  bg-slate-50">
      {children}
    </body>
  );
}
