import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/src/features/layouts/Header";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="iso-8859-1" />
      </Head>
      <body className={inter.className}>
        <Header />
        <div className="flex-1 m-auto py-12" style={{ width: "80%" }}>
          {children}
        </div>
      </body>
    </html>
  );
}
