import { Header } from "@/src/features/layouts/Header";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className={inter.className}>
      <Header />
      <div
        className="flex-1 m-auto py-12 max-w-screen-xl mx-auto"
        style={{ width: "80%" }}
      >
        {children}
      </div>
    </body>
  );
}
